-- 创建 game_categories 表（游戏分类管理）
CREATE TABLE IF NOT EXISTS game_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  icon TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_game_categories_key ON game_categories(key);
CREATE INDEX IF NOT EXISTS idx_game_categories_is_active ON game_categories(is_active);

-- 允许匿名用户访问
ALTER TABLE game_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Allow public read" ON game_categories
  FOR SELECT USING (true);

CREATE POLICY IF NOT EXISTS "Allow public insert" ON game_categories
  FOR INSERT WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Allow public update" ON game_categories
  FOR UPDATE USING (true);

CREATE POLICY IF NOT EXISTS "Allow public delete" ON game_categories
  FOR DELETE USING (true);

-- 创建 version_control 表（版本控制）
CREATE TABLE IF NOT EXISTS version_control (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version TEXT NOT NULL,
  description TEXT,
  changes JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE version_control ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Allow public read" ON version_control
  FOR SELECT USING (true);

CREATE POLICY IF NOT EXISTS "Allow public insert" ON version_control
  FOR INSERT WITH CHECK (true);

-- 插入初始分类数据
INSERT INTO game_categories (key, name, icon, sort_order) VALUES
  ('全部', '全部', '🎮', 0),
  ('王者荣耀', '王者荣耀', '⚔️', 1),
  ('光遇', '光遇', '☁️', 2),
  ('和平精英', '和平精英', '🔫', 3),
  ('英雄联盟', '英雄联盟', '🛡️', 4),
  ('原神', '原神', '✨', 5),
  ('Dota2', 'Dota2', '⚡', 6),
  ('无畏契约', '无畏契约', '💜', 7),
  ('崩坏：星穹铁道', '崩坏：星穹铁道', '🚂', 8),
  ('CS2', 'CS2', '🎯', 9),
  ('蛋仔派对', '蛋仔派对', '🥚', 10),
  ('我的世界', '我的世界', '🏠', 11),
  ('第五人格', '第五人格', '🎭', 12),
  ('金铲铲之战', '金铲铲之战', '🔶', 13),
  ('永劫无间', '永劫无间', '⚔️', 14)
ON CONFLICT (key) DO NOTHING;

-- 记录初始版本
INSERT INTO version_control (version, description, changes)
VALUES (
  '1.0',
  '初始版本，包含10个游戏分类',
  '["王者荣耀", "光遇", "和平精英", "英雄联盟", "原神", "Dota2", "无畏契约", "崩坏：星穹铁道", "CS2"]'
);

INSERT INTO version_control (version, description, changes)
VALUES (
  '1.1',
  '新增5个游戏分类：蛋仔派对、我的世界、第五人格、金铲铲之战、永劫无间',
  '["蛋仔派对", "我的世界", "第五人格", "金铲铲之战", "永劫无间"]'
);
