-- 创建 reviews 表（评价系统）
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  rating NUMERIC(2,1) NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE(club_id, user_id)
);

-- 创建索引
CREATE INDEX idx_reviews_club_id ON reviews(club_id);
CREATE INDEX idx_reviews_user_id ON reviews(user_id);
CREATE INDEX idx_reviews_rating ON reviews(rating);

-- 启用 RLS
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- 安全的 RLS 策略
CREATE POLICY allow_public_read_reviews ON reviews FOR SELECT USING (true);
CREATE POLICY authenticated_users_create_reviews ON reviews FOR INSERT WITH CHECK (auth.uid()::text = user_id);
CREATE POLICY authenticated_users_update_own_reviews ON reviews FOR UPDATE USING (auth.uid()::text = user_id) WITH CHECK (auth.uid()::text = user_id);
CREATE POLICY authenticated_users_delete_own_reviews ON reviews FOR DELETE USING (auth.uid()::text = user_id);

-- 更新 clubs 表的 rating 字段（如果不存在）
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clubs' AND column_name = 'rating') THEN
    ALTER TABLE clubs ADD COLUMN rating NUMERIC(3,1) DEFAULT 0;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clubs' AND column_name = 'review_count') THEN
    ALTER TABLE clubs ADD COLUMN review_count INTEGER DEFAULT 0;
  END IF;
END $$;

-- 创建函数：更新俱乐部评分
CREATE OR REPLACE FUNCTION update_club_rating()
RETURNS TRIGGER AS $$
DECLARE
  target_club_id BIGINT;
BEGIN
  -- 确定要更新的俱乐部 ID
  IF TG_OP = 'DELETE' THEN
    target_club_id = OLD.club_id;
  ELSE
    target_club_id = NEW.club_id;
  END IF;

  -- 更新俱乐部评分和评价数量
  UPDATE clubs
  SET 
    rating = (
      SELECT COALESCE(ROUND(AVG(rating)::numeric, 1), 0)
      FROM reviews
      WHERE club_id = target_club_id
    ),
    review_count = (
      SELECT COUNT(*)
      FROM reviews
      WHERE club_id = target_club_id
    )
  WHERE id = target_club_id;
  
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- 创建触发器
DROP TRIGGER IF EXISTS trigger_update_club_rating ON reviews;
CREATE TRIGGER trigger_update_club_rating
AFTER INSERT OR UPDATE OR DELETE ON reviews
FOR EACH ROW
EXECUTE FUNCTION update_club_rating();
