-- ============================================
-- 🔧 Supabase 认证系统修复脚本
-- 解决 "Database error saving new user" 错误
-- 请在 Supabase SQL Editor 中执行此脚本
-- ============================================

-- 第1步：确保 profiles 表存在
CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID UNIQUE NOT NULL,
  nickname TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 第2步：删除旧的触发器和函数（使用 CASCADE 自动删除依赖对象）
-- 注意：数据库中的触发器可能叫 on_auth_user_created 或 create_profile_on_user_signup
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP TRIGGER IF EXISTS create_profile_on_user_signup ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;

-- 第3步：创建更健壮的 profile 自动创建函数
-- 使用 COALESCE 处理 email 可能为 NULL 的情况
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, nickname, avatar_url, created_at, updated_at)
  VALUES (
    NEW.id,
    COALESCE(
      SPLIT_PART(NEW.email, '@', 1),        -- 取 @ 前面的部分作为昵称
      'user_' || SUBSTRING(NEW.id::text, 1, 8)  -- 如果 email 为空，用 ID 前8位
    ),
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 第4步：重新创建触发器
CREATE TRIGGER create_profile_on_user_signup
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- 第5步：启用 RLS 并创建策略
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- 删除可能存在的旧策略
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can create their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
DROP POLICY IF EXISTS "Users can delete their own profile" ON profiles;

-- 创建新策略
CREATE POLICY "Users can view their own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own profile"
  ON profiles FOR DELETE
  USING (auth.uid() = user_id);

-- 第6步：授予正确的权限
GRANT SELECT, INSERT, UPDATE, DELETE ON profiles TO authenticated;
GRANT SELECT ON profiles TO anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO anon;

-- 第7步：验证修复
SELECT '✅ 认证系统修复完成！' as 状态;

-- 检查 profiles 表
SELECT
  'profiles表存在' as 检查项,
  CASE WHEN EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'profiles'
  ) THEN '✅' ELSE '❌' END as 结果;

-- 检查触发器
SELECT
  'auth触发器存在' as 检查项,
  CASE WHEN EXISTS (
    SELECT 1 FROM information_schema.triggers
    WHERE event_object_schema = 'auth'
    AND event_object_table = 'users'
    AND trigger_name IN ('create_profile_on_user_signup', 'on_auth_user_created')
  ) THEN '✅' ELSE '❌' END as 结果;
