-- ============================================
-- 陪玩俱乐部 - Supabase 数据库初始化脚本
-- 兼容已有表，不删除现有数据
-- ============================================

-- 先检查 clubs 表的 id 类型
DO $$
DECLARE
  club_id_type TEXT;
BEGIN
  SELECT data_type INTO club_id_type
  FROM information_schema.columns
  WHERE table_name = 'clubs' AND column_name = 'id';

  -- 如果 clubs 表不存在，创建它（使用 BIGINT 以兼容 Supabase 默认）
  IF club_id_type IS NULL THEN
    CREATE TABLE clubs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      game TEXT,
      description TEXT DEFAULT '',
      contact TEXT DEFAULT '',
      price_range TEXT DEFAULT '',
      special_services JSONB DEFAULT '[]',
      icon_url TEXT DEFAULT '',
      cover_image_url TEXT DEFAULT '',
      created_by TEXT,
      status TEXT DEFAULT 'pending',
      member_count INTEGER DEFAULT 0,
      rating FLOAT DEFAULT 0,
      review_count INTEGER DEFAULT 0,
      is_official BOOLEAN DEFAULT false,
      founded_year TEXT DEFAULT '',
      activity_frequency TEXT DEFAULT '',
      member_requirement TEXT DEFAULT '',
      detailed_description TEXT DEFAULT '',
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
    RAISE NOTICE 'Created clubs table';
  ELSE
    RAISE NOTICE 'clubs table already exists (id type: %)', club_id_type;
  END IF;
END $$;

-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  status TEXT DEFAULT 'active',
  banned_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 俱乐部成员表（BIGINT club_id 匹配 clubs 表）
CREATE TABLE IF NOT EXISTS club_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  role TEXT DEFAULT 'member',
  joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- 俱乐部管理员表
CREATE TABLE IF NOT EXISTS club_admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  role TEXT DEFAULT 'admin',
  appointed_by TEXT,
  appointed_at TIMESTAMPTZ DEFAULT NOW()
);

-- 申请表
CREATE TABLE IF NOT EXISTS applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);

-- 评分表
CREATE TABLE IF NOT EXISTS club_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 通知表
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 聊天室表
CREATE TABLE IF NOT EXISTS chat_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL,
  type TEXT DEFAULT 'public',
  name TEXT DEFAULT '',
  participant_ids JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 聊天消息表
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT NOT NULL,
  sender_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 俱乐部消息表（公共聊天）
CREATE TABLE IF NOT EXISTS club_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT NOT NULL,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 操作日志表
CREATE TABLE IF NOT EXISTS member_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id BIGINT,
  user_id TEXT,
  action TEXT,
  actor_id TEXT,
  details JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 启用 RLS
-- ============================================
ALTER TABLE IF EXISTS users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS club_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS club_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS club_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS club_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS member_audit_log ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 公开访问策略（删除旧策略后重建，避免冲突）
-- ============================================
DO $$
DECLARE
  tbl TEXT;
BEGIN
  FOR tbl IN
    SELECT unnest(ARRAY['users','clubs','club_members','club_admins','applications','club_ratings','notifications','chat_rooms','chat_messages','club_messages','member_audit_log'])
  LOOP
    -- 删除可能存在的旧策略
    EXECUTE format('DROP POLICY IF EXISTS "Public access" ON %I', tbl);
    -- 创建新策略
    EXECUTE format('CREATE POLICY "Public access" ON %I FOR ALL USING (true) WITH CHECK (true)', tbl);
  END LOOP;
END $$;

-- ============================================
-- Storage bucket（图片上传）
-- ============================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public access to images" ON storage.objects;
CREATE POLICY "Public access to images"
ON storage.objects FOR ALL
USING (true)
WITH CHECK (true);
